import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_Thai} from "next/font/google";
import RootLayoutClient from "./layout/rootLayoutClient"; // Import the client-side layout logic

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noto_Sans_Thai = Noto_Sans_Thai({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={noto_Sans_Thai.className}>
      <body>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
